### ISSUE TITLE
How should we handle technologies or resources across different sites?

### ISSUE THREAD

**Issue by johnjasa** [NREL/H2Integrate#48]
In the `site_config.yaml` we nominally have a top-level site definition.
How should we handle a case where some assets are on or off shore, electrolyzers are clustered elsewhere, we need to transport ore, etc?
Should each technology have an optional `site` entry that overwrites the top-level `site` info if provided? Something else?

**Comment by jaredthomas68** [comment]
Maybe we could specify multiple sub-sites just like we would like to specify sub-systems. In that way we could put groups of technologies and resources at individual sites. Each sub-site could specify available resources at that sub-site and each sub-system would specify the name of the sub-site it should be placed at. Alternatively each tech could specify its site. Only previously available resources would need to be specified at the site level.  If two sub-systems need to pass a given resource (like electricity from offshore plant to onshore plant), then transportation will be required. I'm not sure if that should be specified at a given sub-site or as a separate entry connecting sites. Something like this:

```yaml
sites:
    site-name-1:
        offshore: false
        lat: xxx.xxx
        lon: xxx.xxx
        resources:
            wind: "wind.csv"
            electricity: "electricity.csv"
    site-name-2:
        offshore: true
        lat: xxx.xxx
        lon: xxx.xxx
        resources:
            solar: "solar.csv"
    transport-site-1:
        nodes:
            0:
                lat: xxx.xxx
                lon: xxx.xxx
            1: 
                lat: xxx.xxx
                lon: xxx.xxx

systems:
    system-1:
        site: "site-name-1"
    system-2:
        site: "site-name-2"
    system-3:
        site: "transport-site-1"
```
